#!/bin/bash

echo "========================================="
echo "🔥 FIREBASE USAGE AUDIT"
echo "========================================="
echo ""

echo "1️⃣ Package Dependencies:"
echo "Root package.json:"
grep -i firebase package.json 2>/dev/null || echo "  ✅ No Firebase in root"
echo ""
echo "Client package.json:"
grep -i firebase client/package.json 2>/dev/null || echo "  ✅ No Firebase in client"
echo ""
echo "Server package.json:"
grep -i firebase server/package.json 2>/dev/null || echo "  ✅ No Firebase in server"

echo ""
echo "2️⃣ Configuration Files:"
ls -la firebase.json .firebaserc firestore.rules firestore.indexes.json 2>/dev/null || echo "  ✅ No Firebase config files"

echo ""
echo "3️⃣ Code References:"
echo "Client code:"
find client/src -name "*.ts" -o -name "*.tsx" 2>/dev/null | xargs grep -l "firebase" 2>/dev/null || echo "  ✅ No Firebase imports"
echo ""
echo "Server code:"
find server -name "*.ts" -o -name "*.js" 2>/dev/null | xargs grep -l "firebase" 2>/dev/null || echo "  ✅ No Firebase imports"

echo ""
echo "4️⃣ Environment Variables:"
echo "Checking for Firebase env vars..."
grep -i firebase .env* 2>/dev/null || echo "  ✅ No Firebase env vars in local .env files"

echo ""
echo "5️⃣ Database Check:"
echo "Current database configuration:"
grep -h "DATABASE\|POSTGRES\|DB_" .env* 2>/dev/null | head -5 || echo "  (Check Render dashboard for DATABASE_URL)"

echo ""
echo "6️⃣ Quick grep for 'firebase' anywhere:"
grep -r "firebase" . --include="*.json" --include="*.ts" --include="*.tsx" --include="*.js" --max-count=3 2>/dev/null || echo "  ✅ No 'firebase' found in codebase"

echo ""
echo "========================================="
echo "SUMMARY"
echo "========================================="
echo "Your infrastructure based on our work:"
echo "  ✅ Hosting: Render (srv-d4jtmm49c44c73eioqc0)"
echo "  ✅ Database: PostgreSQL on Render"
echo "  ✅ Frontend: React + TypeScript + Vite"
echo "  ✅ Backend: Node.js + Express"
echo "  ✅ CDN/DNS: Cloudflare (proxying traffic)"
echo "  ✅ APIs: Stripe, SendGrid, Twilio, Google Places"
echo ""
echo "Firebase status will be shown above ☝️"
echo "========================================="
