
CREATE TABLE IF NOT EXISTS cancellation_feedback (id serial PRIMARY KEY, household_id varchar(255), reason varchar(50), feedback text, created_at timestamp DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS email_events (id serial PRIMARY KEY, household_id varchar(255), email_type varchar(50) NOT NULL, sent_at timestamp DEFAULT now() NOT NULL, opened_at timestamp, clicked_at timestamp, bounced boolean DEFAULT false, error_message text);
CREATE TABLE IF NOT EXISTS feature_permissions (id serial PRIMARY KEY, subscription_tier varchar(20) NOT NULL, feature_key varchar(50) NOT NULL, enabled boolean DEFAULT true, limit_value integer);
CREATE TABLE IF NOT EXISTS magic_links (id varchar PRIMARY KEY DEFAULT gen_random_uuid(), token varchar(64) NOT NULL UNIQUE, email varchar(255) NOT NULL, household_id varchar(255), expires_at timestamp NOT NULL, used boolean DEFAULT false, used_at timestamp, created_at timestamp DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS signup_attempts (id serial PRIMARY KEY, email varchar(255) NOT NULL, canonical_email varchar(255), ip_address varchar(45), user_agent text, device_fingerprint varchar(255), success boolean DEFAULT false, error_message text, created_at timestamp DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS subscription_events (id serial PRIMARY KEY, household_id varchar(255), stripe_event_type varchar(100) NOT NULL, stripe_event_id varchar(255) NOT NULL UNIQUE, subscription_status_before varchar(30), subscription_status_after varchar(30), metadata jsonb, processing_error text, created_at timestamp DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS warranty_notifications (id varchar PRIMARY KEY DEFAULT gen_random_uuid(), household_appliance_id varchar(255) NOT NULL, household_id varchar(255) NOT NULL, notification_type varchar(20) NOT NULL, notification_method varchar(20) NOT NULL, email_sent boolean DEFAULT false, sms_sent boolean DEFAULT false, email_sent_at timestamp, sms_sent_at timestamp, status varchar(20) DEFAULT 'pending' NOT NULL, error_message text, created_at timestamp DEFAULT now() NOT NULL, updated_at timestamp DEFAULT now() NOT NULL);
ALTER TABLE households ADD COLUMN IF NOT EXISTS subscription_tier varchar(20) DEFAULT 'basic';
ALTER TABLE households ADD COLUMN IF NOT EXISTS billing_interval varchar(20);
ALTER TABLE households ADD COLUMN IF NOT EXISTS subscription_status varchar(30) DEFAULT 'incomplete';
ALTER TABLE households ADD COLUMN IF NOT EXISTS trial_starts_at timestamp;
ALTER TABLE households ADD COLUMN IF NOT EXISTS trial_ends_at timestamp;
ALTER TABLE households ADD COLUMN IF NOT EXISTS trial_used boolean DEFAULT false;
ALTER TABLE households ADD COLUMN IF NOT EXISTS first_payment_attempt_at timestamp;
ALTER TABLE households ADD COLUMN IF NOT EXISTS grace_period_ends_at timestamp;
ALTER TABLE households ADD COLUMN IF NOT EXISTS email_verified boolean DEFAULT false;
ALTER TABLE households ADD COLUMN IF NOT EXISTS email_verification_token varchar(255);
ALTER TABLE households ADD COLUMN IF NOT EXISTS email_verified_at timestamp;
ALTER TABLE households ADD COLUMN IF NOT EXISTS stripe_customer_id varchar(255);
ALTER TABLE households ADD COLUMN IF NOT EXISTS stripe_subscription_id varchar(255);
ALTER TABLE households ADD COLUMN IF NOT EXISTS stripe_payment_method_id varchar(255);
ALTER TABLE households ADD COLUMN IF NOT EXISTS canonical_email varchar(255);
ALTER TABLE households ADD COLUMN IF NOT EXISTS terms_accepted_at timestamp;
ALTER TABLE households ADD COLUMN IF NOT EXISTS privacy_accepted_at timestamp;
ALTER TABLE households ADD COLUMN IF NOT EXISTS signup_ip_address varchar(45);
ALTER TABLE households ADD COLUMN IF NOT EXISTS signup_user_agent text;
ALTER TABLE households ADD COLUMN IF NOT EXISTS onboarding_completed boolean DEFAULT false;
ALTER TABLE households ADD COLUMN IF NOT EXISTS payment_added_at timestamp;
ALTER TABLE households ADD COLUMN IF NOT EXISTS canceled_at timestamp;
ALTER TABLE households ADD COLUMN IF NOT EXISTS cancellation_reason text;
ALTER TABLE households ADD COLUMN IF NOT EXISTS cancellation_type varchar(30);
ALTER TABLE households ADD COLUMN IF NOT EXISTS cancellation_source varchar(50);
ALTER TABLE households ADD COLUMN IF NOT EXISTS cancel_at_period_end boolean DEFAULT false;
ALTER TABLE households ADD COLUMN IF NOT EXISTS first_qr_scan_at timestamp;
ALTER TABLE households ADD COLUMN IF NOT EXISTS first_maintenance_task_at timestamp;
ALTER TABLE households ADD COLUMN IF NOT EXISTS sms_enabled_at timestamp;
ALTER TABLE order_magnet_items ADD COLUMN IF NOT EXISTS household_id varchar(255);
CREATE INDEX IF NOT EXISTS idx_households_subscription_status ON households (subscription_status);
CREATE INDEX IF NOT EXISTS idx_households_trial_ends_at ON households (trial_ends_at);
CREATE INDEX IF NOT EXISTS idx_households_stripe_customer_id ON households (stripe_customer_id);
CREATE INDEX IF NOT EXISTS idx_households_trial_used ON households (trial_used);
CREATE INDEX IF NOT EXISTS idx_households_grace_period ON households (grace_period_ends_at);
CREATE INDEX IF NOT EXISTS idx_households_canonical_email ON households (canonical_email);
CREATE INDEX IF NOT EXISTS idx_sub_events_household_id ON subscription_events (household_id);
CREATE INDEX IF NOT EXISTS idx_sub_events_type ON subscription_events (stripe_event_type);
CREATE INDEX IF NOT EXISTS idx_sub_events_created_at ON subscription_events (created_at);
CREATE INDEX IF NOT EXISTS idx_email_events_household_id ON email_events (household_id);
CREATE INDEX IF NOT EXISTS idx_email_events_type ON email_events (email_type);
CREATE UNIQUE INDEX IF NOT EXISTS idx_feature_perm_tier_key ON feature_permissions (subscription_tier, feature_key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_magic_links_token ON magic_links (token);
CREATE INDEX IF NOT EXISTS idx_magic_links_email ON magic_links (email);
CREATE INDEX IF NOT EXISTS idx_magic_links_expires ON magic_links (expires_at);
CREATE INDEX IF NOT EXISTS idx_signup_attempts_email ON signup_attempts (email);
CREATE INDEX IF NOT EXISTS idx_signup_attempts_canonical ON signup_attempts (canonical_email);
CREATE INDEX IF NOT EXISTS idx_signup_attempts_ip ON signup_attempts (ip_address);
CREATE INDEX IF NOT EXISTS idx_signup_attempts_fingerprint ON signup_attempts (device_fingerprint);
