-- Seed data for home maintenance tasks catalog
-- Run this once to populate the task templates
-- Safe to re-run: Uses ON CONFLICT to prevent duplicates

INSERT INTO home_maintenance_tasks (
  task_code,
  category,
  task_name,
  base_frequency,
  months_hot_humid,
  months_cold_snow,
  months_mixed,
  months_arid_mountain,
  seasonal_tag,
  how_to,
  why_it_matters,
  est_minutes,
  materials,
  safety_note,
  applies_if_freeze,
  applies_if_hurricane,
  applies_if_wildfire,
  applies_if_hard_water,
  applies_if_has_sprinklers,
  pro_service_recommended,
  diy_ok
) VALUES

-- HVAC Tasks
(
  'HVAC_FILTER_CHANGE',
  'HVAC',
  'Change HVAC Air Filter',
  'monthly',
  'monthly',
  'monthly',
  'monthly',
  'monthly',
  NULL,
  'Turn off HVAC system. Locate air filter (usually in return air duct or furnace). Remove old filter, noting size and direction of airflow arrow. Insert new filter with arrow pointing toward furnace/blower. Turn system back on.',
  'Clean filters improve air quality, reduce energy costs by 5-15%, and prevent system breakdowns. Dirty filters force your HVAC to work harder, shortening its lifespan.',
  15,
  'Replacement HVAC filter (check size: common sizes are 16x20x1, 20x25x1)',
  'Turn off system before replacing filter to avoid inhaling dust.',
  false,
  false,
  false,
  false,
  false,
  false,
  true
),

(
  'HVAC_ANNUAL_SERVICE',
  'HVAC',
  'Schedule Professional HVAC Inspection',
  'annual',
  'spring',
  'spring',
  'spring',
  'spring',
  'spring',
  'Contact licensed HVAC technician to inspect system before cooling season. Technician will check refrigerant levels, clean coils, test thermostat, inspect electrical connections, and ensure proper airflow.',
  'Annual maintenance extends HVAC lifespan by 5-10 years, prevents costly breakdowns, maintains warranty coverage, and keeps energy efficiency optimal.',
  90,
  'None (professional service)',
  'Ensure technician is licensed and insured.',
  false,
  false,
  false,
  false,
  false,
  true,
  false
),

(
  'HVAC_CONDENSER_CLEAN',
  'HVAC',
  'Clean Outdoor AC Condenser Unit',
  'annual',
  'spring',
  'spring',
  'spring',
  'spring',
  'spring',
  'Turn off power to unit at breaker. Remove debris (leaves, grass) from around unit. Gently spray coils with garden hose from inside out. Straighten any bent fins with fin comb. Clear 2-foot perimeter around unit.',
  'Clean condensers run 10-15% more efficiently, reduce cooling costs, and prevent compressor failure. Blocked airflow is a leading cause of AC failure.',
  30,
  'Garden hose, fin comb (optional)',
  'Always turn off power at breaker before cleaning. Never use pressure washer.',
  false,
  false,
  false,
  false,
  false,
  false,
  true
),

-- Plumbing Tasks
(
  'WATER_HEATER_FLUSH',
  'Plumbing',
  'Flush Water Heater Tank',
  'annual',
  'annual',
  'annual',
  'annual',
  'annual',
  NULL,
  'Turn off power/gas to heater. Attach hose to drain valve at bottom of tank. Run hose to drain or outside. Open drain valve and let tank drain completely (20-30 minutes). Close valve, remove hose, turn power/gas back on.',
  'Removes sediment buildup that reduces efficiency, causes noisy operation, and shortens tank life. Can improve efficiency by 5-10% and extend tank life by years.',
  45,
  'Garden hose, bucket',
  'Water will be HOT. Let cool for 2 hours before draining or wear protective gloves.',
  false,
  false,
  false,
  true,
  false,
  false,
  true
),

(
  'WATER_HEATER_ANODE',
  'Plumbing',
  'Inspect Water Heater Anode Rod',
  'biannual',
  'biannual',
  'biannual',
  'biannual',
  'biannual',
  NULL,
  'Turn off power/gas. Locate anode rod on top of tank. Use socket wrench to remove rod. If rod is less than 1/2" thick or coated with calcium, replace it. Apply teflon tape to threads and reinstall.',
  'Anode rod prevents tank corrosion by sacrificing itself. Replacing it can extend tank life from 8-10 years to 15-20 years. Most important preventive maintenance for water heaters.',
  60,
  'Socket wrench, replacement anode rod, teflon tape',
  'Turn off power/gas. If rod is stuck, consider calling professional.',
  false,
  false,
  false,
  true,
  false,
  true,
  false
),

(
  'LEAK_INSPECTION',
  'Plumbing',
  'Check for Plumbing Leaks',
  'quarterly',
  'quarterly',
  'quarterly',
  'quarterly',
  'quarterly',
  NULL,
  'Inspect under sinks, around toilets, water heater, and washing machine. Look for water stains, moisture, mold, or dripping. Check water meter: turn off all water, note meter reading, wait 2 hours, check again. If meter changed, you have a leak.',
  'Small leaks waste 10,000+ gallons per year, cause water damage ($5,000-$70,000 repairs), promote mold growth, and increase water bills. Early detection prevents major damage.',
  20,
  'Flashlight',
  'Check for mold/mildew which indicates moisture problems.',
  false,
  false,
  false,
  false,
  false,
  false,
  true
),

-- Exterior Tasks
(
  'GUTTER_CLEANING',
  'Exterior',
  'Clean Gutters and Downspouts',
  'biannual',
  'spring-fall',
  'spring-fall',
  'spring-fall',
  'spring-fall',
  'spring-fall',
  'Use sturdy ladder with stabilizer. Scoop debris from gutters into bucket. Flush gutters with hose. Check downspouts are clear. Ensure water flows away from foundation.',
  'Clogged gutters cause water damage to roof, siding, foundation ($10,000-$50,000 repairs), basement flooding, and landscape erosion. Regular cleaning prevents these costly issues.',
  60,
  'Ladder, gloves, bucket, garden hose, gutter scoop',
  'Use ladder stabilizer. Never lean ladder against gutters. Work with partner.',
  false,
  false,
  false,
  false,
  false,
  false,
  true
),

(
  'ROOF_INSPECTION',
  'Exterior',
  'Visual Roof Inspection',
  'annual',
  'spring',
  'spring',
  'spring',
  'spring',
  'spring',
  'From ground with binoculars, look for missing/damaged shingles, sagging areas, damaged flashing around chimneys/vents. Inside attic, check for water stains, daylight through roof, or sagging.',
  'Early detection of roof issues prevents major water damage, mold, and structural problems. Small repairs cost $300-$1,000; replacement costs $5,000-$15,000+.',
  30,
  'Binoculars, flashlight',
  'Do NOT climb on roof yourself - hire professional if issues found.',
  false,
  true,
  false,
  false,
  false,
  true,
  true
),

(
  'PRESSURE_WASH',
  'Exterior',
  'Pressure Wash Exterior',
  'annual',
  'spring',
  'spring',
  'spring',
  'spring',
  'spring',
  'Rent or use pressure washer (1500-2000 PSI for home). Start from top, work down. Keep nozzle 12-18" from surface. Use wide-angle nozzle. Avoid windows, vents, and electrical fixtures.',
  'Removes mold, mildew, dirt, and grime that degrade siding. Maintains curb appeal, prevents rot, and extends siding life. Increases home value by $10,000-$15,000.',
  120,
  'Pressure washer, safety goggles, outdoor cleaner',
  'Never use on damaged siding. Wear safety goggles. Keep nozzle moving to avoid damage.',
  false,
  false,
  false,
  false,
  false,
  false,
  true
),

-- Seasonal Tasks
(
  'WINTERIZATION',
  'Seasonal',
  'Winterize Home',
  'annual',
  NULL,
  'fall',
  'fall',
  'fall',
  'fall',
  'Drain and shut off outdoor faucets. Insulate exposed pipes. Clean and store garden hoses. Service snow removal equipment. Check weatherstripping on doors/windows. Test heating system.',
  'Prevents frozen pipe bursts ($5,000+ damage), reduces heating costs by 10-20%, ensures heating system works when needed, prevents carbon monoxide issues.',
  90,
  'Pipe insulation, weatherstripping',
  'Test smoke and CO detectors. Have heating system serviced professionally.',
  true,
  false,
  false,
  false,
  false,
  false,
  true
),

(
  'SPRING_MAINTENANCE',
  'Seasonal',
  'Spring Home Maintenance',
  'annual',
  'spring',
  'spring',
  'spring',
  'spring',
  'spring',
  'Inspect roof and gutters. Check for winter damage. Turn on outdoor water faucets. Test sprinkler system. Clean windows. Check AC system. Inspect deck/patio for damage.',
  'Addresses winter damage before it worsens. Prepares home for summer. Prevents small issues from becoming expensive repairs. Maintains home value.',
  120,
  'Various tools and supplies',
  'Inspect for pest damage after winter.',
  false,
  false,
  false,
  false,
  true,
  false,
  true
),

-- Appliance Tasks
(
  'DRYER_VENT_CLEAN',
  'Appliance',
  'Clean Dryer Vent',
  'annual',
  'annual',
  'annual',
  'annual',
  'annual',
  NULL,
  'Unplug dryer. Disconnect vent hose from back of dryer and wall. Use dryer vent brush or vacuum to remove lint from hose and duct. Reconnect securely. Clean lint trap.',
  'Lint buildup causes 15,000+ house fires annually. Cleaning improves drying efficiency (30% faster), reduces energy costs, prevents fires, and extends dryer life.',
  45,
  'Dryer vent brush kit or vacuum attachment',
  'Unplug dryer before cleaning. Check for gas leaks if gas dryer.',
  false,
  false,
  true,
  false,
  false,
  false,
  true
),

(
  'FRIDGE_COILS_CLEAN',
  'Appliance',
  'Clean Refrigerator Coils',
  'annual',
  'annual',
  'annual',
  'annual',
  'annual',
  NULL,
  'Unplug refrigerator. Locate coils (usually back or bottom behind panel). Use coil brush or vacuum to remove dust and debris. Clean area around fridge. Plug back in.',
  'Dirty coils make fridge work 25% harder, shortening lifespan and increasing energy costs by $100+/year. Cleaning takes 15 minutes, extends fridge life by years.',
  30,
  'Coil cleaning brush or vacuum with brush attachment',
  'Unplug before cleaning. Be gentle with coils - they bend easily.',
  false,
  false,
  false,
  false,
  false,
  false,
  true
),

-- Safety Tasks
(
  'SMOKE_DETECTOR_TEST',
  'Safety',
  'Test Smoke and CO Detectors',
  'monthly',
  'monthly',
  'monthly',
  'monthly',
  'monthly',
  NULL,
  'Press test button on each detector. Should sound alarm. If not, replace battery. Replace entire unit every 10 years. Vacuum detector to remove dust.',
  'Working detectors are required by law and save lives. Smoke alarms cut fire death risk by 50%. CO detectors prevent poisoning deaths. Simple test takes 5 minutes.',
  10,
  'Replacement batteries (9V or AA)',
  'Never disable detector. Replace if more than 10 years old.',
  false,
  false,
  true,
  false,
  false,
  false,
  true
),

(
  'FIRE_EXTINGUISHER_CHECK',
  'Safety',
  'Inspect Fire Extinguishers',
  'monthly',
  'monthly',
  'monthly',
  'monthly',
  'monthly',
  NULL,
  'Check pressure gauge is in green zone. Ensure pin and seal are intact. Check for visible damage or corrosion. Ensure accessible and not blocked. Should have one per floor and in kitchen.',
  'Quick access to working extinguisher can prevent small fire from becoming total loss ($100,000+ damage). 90% of home fires start small and could be stopped with extinguisher.',
  5,
  'None',
  'Never use water on electrical or grease fires. Call 911 for any fire.',
  false,
  false,
  true,
  false,
  false,
  false,
  true
),

-- HVAC Seasonal
(
  'FURNACE_FILTER_WINTER',
  'HVAC',
  'Change Furnace Filter (Winter)',
  'monthly',
  NULL,
  'monthly',
  'monthly',
  'monthly',
  'winter',
  'Turn off furnace. Locate filter (usually in return duct or furnace). Remove old filter. Note size and airflow direction. Install new filter with arrow pointing toward furnace. Turn system back on.',
  'Critical during heating season when furnace runs constantly. Clean filter prevents furnace overheating, reduces heating costs by 15%, improves air quality, extends furnace life.',
  15,
  'Furnace filter (check size - common: 16x20x1, 20x25x1)',
  'Turn off furnace before replacing. Consider higher MERV rating for better filtration.',
  true,
  false,
  false,
  false,
  false,
  false,
  true
),

-- Exterior Paint/Siding
(
  'CAULK_INSPECTION',
  'Exterior',
  'Inspect and Replace Caulking',
  'annual',
  'spring',
  'spring',
  'spring',
  'spring',
  'spring',
  'Check caulking around windows, doors, and exterior penetrations (pipes, wires). Look for cracks, gaps, or missing caulk. Remove old deteriorated caulk. Apply new exterior-grade silicone caulk.',
  'Failed caulking allows water infiltration causing rot, mold, insect entry, and energy loss. Small caulk job ($20) prevents thousands in water damage repairs.',
  60,
  'Caulk gun, exterior silicone caulk, caulk removal tool',
  'Work in dry conditions. Caulk requires 24 hours to cure.',
  false,
  true,
  false,
  false,
  false,
  false,
  true
),

-- Lawn/Sprinkler
(
  'SPRINKLER_WINTERIZE',
  'Exterior',
  'Winterize Sprinkler System',
  'annual',
  NULL,
  'fall',
  'fall',
  'fall',
  'fall',
  'Turn off water supply to system. Drain pipes using manual drain valves or compressed air blowout. Open valves to release pressure. Insulate backflow preventer.',
  'Prevents pipe bursts from freezing ($2,000-$5,000 repairs). Critical in cold climates. Spring repairs cost 3x more than fall winterization.',
  60,
  'Air compressor (if using blowout method)',
  'If using compressed air, do not exceed 80 PSI for PVC pipes.',
  true,
  false,
  false,
  false,
  true,
  true,
  false
),

(
  'SPRINKLER_SPRING_START',
  'Exterior',
  'Start Up Sprinkler System',
  'annual',
  'spring',
  'spring',
  'spring',
  'spring',
  'spring',
  'Slowly turn on water supply. Check each zone for leaks, broken heads, or poor coverage. Adjust spray patterns. Set controller for seasonal schedule.',
  'Proper startup prevents water waste, dead zones in lawn, and high water bills. Catches winter damage early when repairs are cheaper.',
  45,
  'Screwdriver for adjustments',
  'Turn on water slowly to avoid pressure damage.',
  false,
  false,
  false,
  false,
  true,
  false,
  true
),

-- Deck/Patio
(
  'DECK_SEAL',
  'Exterior',
  'Seal/Stain Deck',
  'biannual',
  'spring',
  'spring',
  'spring',
  'spring',
  'spring',
  'Clean deck thoroughly. Sand rough spots. Apply deck cleaner and brightener. Let dry 48 hours. Apply stain/sealant with brush or roller. Apply thin, even coats.',
  'Sealing prevents wood rot, splintering, UV damage, and insect infestation. Extends deck life from 10-15 years to 25-30 years. Maintains home value.',
  240,
  'Deck cleaner, sander, stain/sealant, brushes/roller',
  'Work in dry weather (no rain for 48 hours). Test stain color on small area first.',
  false,
  false,
  false,
  false,
  false,
  false,
  true
)
ON CONFLICT (task_code) DO NOTHING;
