import { db } from '../db.js';
import { homeMaintenanceTasksTable } from '../../shared/schema';

const MAINTENANCE_TASKS = [
  {
    taskCode: 'HVAC_FILTER_CHANGE',
    category: 'HVAC',
    taskName: 'Change HVAC Air Filter',
    baseFrequency: 'monthly',
    monthsHotHumid: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsColdSnow: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsMixed: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsAridMountain: '1,2,3,4,5,6,7,8,9,10,11,12',
    seasonalTag: null,
    howTo: '1. Turn off HVAC system\n2. Locate filter slot (usually near return air vent)\n3. Remove old filter, note the size\n4. Insert new filter with airflow arrows pointing toward unit\n5. Close slot and restart system',
    whyItMatters: 'Clean filters improve air quality, reduce energy costs by 5-15%, and extend HVAC lifespan by preventing dust buildup on coils and motors.',
    estMinutes: 15,
    materials: 'Replacement filter (check size on current filter)',
    safetyNote: 'Always turn off system before replacing filter',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'HVAC_ANNUAL_SERVICE',
    category: 'HVAC',
    taskName: 'Schedule Annual HVAC Service',
    baseFrequency: 'annually',
    monthsHotHumid: '3,4',
    monthsColdSnow: '9,10',
    monthsMixed: '3,4',
    monthsAridMountain: '3,4',
    seasonalTag: 'spring',
    howTo: '1. Contact your HVAC service provider\n2. Schedule tune-up before peak season\n3. Ask about refrigerant levels and coil cleaning\n4. Request efficiency assessment',
    whyItMatters: 'Professional maintenance prevents costly breakdowns, ensures safety, maintains warranty, and keeps system running at peak efficiency.',
    estMinutes: 120,
    materials: null,
    safetyNote: 'Must be performed by licensed HVAC technician',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: true,
    diyOk: false
  },
  {
    taskCode: 'HVAC_CONDENSER_CLEAN',
    category: 'HVAC',
    taskName: 'Clean Outdoor AC Condenser',
    baseFrequency: 'seasonal',
    monthsHotHumid: '4,5',
    monthsColdSnow: '4,5',
    monthsMixed: '4,5',
    monthsAridMountain: '4,5',
    seasonalTag: 'spring',
    howTo: '1. Turn off power to unit\n2. Clear debris within 2 feet of unit\n3. Gently spray fins with garden hose (not pressure washer)\n4. Straighten bent fins with fin comb if needed\n5. Check that unit is level',
    whyItMatters: 'A clean condenser runs more efficiently, reducing cooling costs by up to 10% and preventing overheating damage.',
    estMinutes: 45,
    materials: 'Garden hose, fin comb (optional)',
    safetyNote: 'Turn off power at breaker before cleaning',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'FURNACE_INSPECTION',
    category: 'HVAC',
    taskName: 'Furnace Pre-Winter Inspection',
    baseFrequency: 'annually',
    monthsHotHumid: null,
    monthsColdSnow: '9,10',
    monthsMixed: '9,10',
    monthsAridMountain: '9,10',
    seasonalTag: 'fall',
    howTo: '1. Schedule professional inspection\n2. Technician will check heat exchanger for cracks\n3. Test safety controls and ignition\n4. Inspect venting and gas connections\n5. Verify thermostat operation',
    whyItMatters: 'Cracked heat exchangers can leak carbon monoxide. Annual inspection ensures safe, reliable heating all winter.',
    estMinutes: 90,
    materials: null,
    safetyNote: 'Carbon monoxide risk - professional inspection required',
    appliesIfFreeze: true,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: true,
    diyOk: false
  },
  {
    taskCode: 'WATER_HEATER_FLUSH',
    category: 'Plumbing',
    taskName: 'Flush Water Heater Tank',
    baseFrequency: 'annually',
    monthsHotHumid: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsColdSnow: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsMixed: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsAridMountain: '1,2,3,4,5,6,7,8,9,10,11,12',
    seasonalTag: null,
    howTo: '1. Turn off water heater (gas or electric)\n2. Connect garden hose to drain valve at bottom\n3. Run hose to floor drain or outside\n4. Open drain valve and let tank empty\n5. Turn on cold water briefly to flush sediment\n6. Close drain, refill tank, restore power',
    whyItMatters: 'Sediment buildup reduces efficiency, causes rumbling noises, and shortens tank life. Flushing extends heater life by 2-5 years.',
    estMinutes: 60,
    materials: 'Garden hose',
    safetyNote: 'Water will be very hot - use caution. Gas units: turn off pilot light',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: true,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'WATER_HEATER_ANODE',
    category: 'Plumbing',
    taskName: 'Check Water Heater Anode Rod',
    baseFrequency: 'annually',
    monthsHotHumid: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsColdSnow: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsMixed: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsAridMountain: '1,2,3,4,5,6,7,8,9,10,11,12',
    seasonalTag: null,
    howTo: '1. Turn off water heater\n2. Locate anode rod port on top of tank\n3. Use 1 1/16" socket to remove rod\n4. If rod is less than 1/2" thick or coated with calcium, replace\n5. Apply teflon tape to new rod threads\n6. Install new rod and hand-tighten',
    whyItMatters: 'The anode rod prevents tank corrosion. A worn rod means your tank is rusting from inside, leading to premature failure and potential flooding.',
    estMinutes: 45,
    materials: '1 1/16" socket, replacement anode rod, teflon tape',
    safetyNote: 'Turn off power and water before inspection',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: true,
    appliesIfHasSprinklers: false,
    proServiceRecommended: true,
    diyOk: true
  },
  {
    taskCode: 'LEAK_INSPECTION',
    category: 'Plumbing',
    taskName: 'Check for Water Leaks',
    baseFrequency: 'quarterly',
    monthsHotHumid: '1,4,7,10',
    monthsColdSnow: '1,4,7,10',
    monthsMixed: '1,4,7,10',
    monthsAridMountain: '1,4,7,10',
    seasonalTag: null,
    howTo: '1. Check under all sinks for moisture or drips\n2. Inspect toilet bases for water stains\n3. Look for water stains on ceilings below bathrooms\n4. Check water heater area for moisture\n5. Inspect washing machine hoses\n6. Look at outdoor hose bibs for drips',
    whyItMatters: 'Small leaks waste thousands of gallons yearly and cause mold, rot, and structural damage. Early detection saves thousands in repairs.',
    estMinutes: 30,
    materials: null,
    safetyNote: null,
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'DRAIN_MAINTENANCE',
    category: 'Plumbing',
    taskName: 'Clean Sink and Shower Drains',
    baseFrequency: 'monthly',
    monthsHotHumid: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsColdSnow: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsMixed: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsAridMountain: '1,2,3,4,5,6,7,8,9,10,11,12',
    seasonalTag: null,
    howTo: '1. Remove drain covers\n2. Pull out hair and debris with drain snake or zip tool\n3. Pour 1/2 cup baking soda followed by 1/2 cup vinegar\n4. Wait 15 minutes, then flush with hot water\n5. Replace drain covers',
    whyItMatters: 'Regular maintenance prevents slow drains and clogs. Avoiding chemical drain cleaners protects your pipes from corrosion.',
    estMinutes: 20,
    materials: 'Drain snake or zip tool, baking soda, white vinegar',
    safetyNote: 'Never mix chemical drain cleaners',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'GUTTER_CLEANING',
    category: 'Exterior',
    taskName: 'Clean Gutters and Downspouts',
    baseFrequency: 'seasonal',
    monthsHotHumid: '4,5,10,11',
    monthsColdSnow: '4,5,10,11',
    monthsMixed: '4,5,10,11',
    monthsAridMountain: '4,5,10,11',
    seasonalTag: 'spring,fall',
    howTo: '1. Set up ladder on stable ground\n2. Scoop debris into bucket\n3. Flush gutters with garden hose\n4. Check downspout flow\n5. Clear any clogs with plumber snake\n6. Check gutter slope (should flow toward downspouts)',
    whyItMatters: 'Clogged gutters cause ice dams, foundation damage, basement flooding, and fascia rot. Regular cleaning prevents thousands in water damage.',
    estMinutes: 90,
    materials: 'Ladder, work gloves, bucket, garden hose',
    safetyNote: 'Use ladder safely - have someone spot you. Consider professional help for multi-story homes.',
    appliesIfFreeze: true,
    appliesIfHurricane: true,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: true,
    diyOk: true
  },
  {
    taskCode: 'ROOF_INSPECTION',
    category: 'Exterior',
    taskName: 'Visual Roof Inspection',
    baseFrequency: 'annually',
    monthsHotHumid: '4,5',
    monthsColdSnow: '4,5',
    monthsMixed: '4,5',
    monthsAridMountain: '4,5',
    seasonalTag: 'spring',
    howTo: '1. Inspect from ground with binoculars\n2. Look for missing, cracked, or curling shingles\n3. Check flashing around chimneys, vents, skylights\n4. Look for sagging areas or moss growth\n5. Check attic for daylight or water stains\n6. Document any issues with photos',
    whyItMatters: 'Small roof problems become major leaks. Early detection of issues can extend roof life and prevent interior water damage.',
    estMinutes: 45,
    materials: 'Binoculars, camera',
    safetyNote: 'Do not walk on roof unless trained. Consider professional inspection for thorough assessment.',
    appliesIfFreeze: false,
    appliesIfHurricane: true,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: true,
    diyOk: true
  },
  {
    taskCode: 'PRESSURE_WASH',
    category: 'Exterior',
    taskName: 'Pressure Wash Exterior',
    baseFrequency: 'annually',
    monthsHotHumid: '3,4',
    monthsColdSnow: '4,5',
    monthsMixed: '4,5',
    monthsAridMountain: '4,5',
    seasonalTag: 'spring',
    howTo: '1. Rent or buy pressure washer (1500-2000 PSI for most surfaces)\n2. Clear area of furniture and debris\n3. Test on inconspicuous area first\n4. Work from top to bottom\n5. Use appropriate PSI for each surface\n6. Let surfaces dry completely',
    whyItMatters: 'Removes mold, mildew, and dirt that degrade surfaces. Extends life of siding, decks, and walkways while improving curb appeal.',
    estMinutes: 180,
    materials: 'Pressure washer, appropriate nozzles, safety goggles',
    safetyNote: 'Never aim at people, pets, or windows. Too much pressure damages wood and siding.',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: true,
    diyOk: true
  },
  {
    taskCode: 'DECK_SEAL',
    category: 'Exterior',
    taskName: 'Inspect and Seal Deck',
    baseFrequency: 'annually',
    monthsHotHumid: '4,5',
    monthsColdSnow: '5,6',
    monthsMixed: '4,5',
    monthsAridMountain: '4,5',
    seasonalTag: 'spring',
    howTo: '1. Clean deck thoroughly (pressure wash or scrub)\n2. Check for loose boards, nails, or rot\n3. Replace damaged boards\n4. Let deck dry 48 hours after cleaning\n5. Apply stain or sealer with brush or sprayer\n6. Allow to dry per product instructions',
    whyItMatters: 'Sealing prevents water damage, UV fading, and premature rot. An unsealed deck may need replacement years earlier.',
    estMinutes: 240,
    materials: 'Deck cleaner, stain/sealer, brushes/sprayer, replacement boards if needed',
    safetyNote: 'Work in well-ventilated area. Follow sealer safety instructions.',
    appliesIfFreeze: true,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: true,
    diyOk: true
  },
  {
    taskCode: 'CAULK_INSPECTION',
    category: 'Exterior',
    taskName: 'Check Exterior Caulk and Seals',
    baseFrequency: 'annually',
    monthsHotHumid: '9,10',
    monthsColdSnow: '9,10',
    monthsMixed: '9,10',
    monthsAridMountain: '9,10',
    seasonalTag: 'fall',
    howTo: '1. Inspect caulk around windows and doors\n2. Check where siding meets trim\n3. Look at penetrations (wires, pipes, vents)\n4. Remove old, cracked caulk with scraper\n5. Clean area and let dry\n6. Apply new exterior caulk in smooth bead',
    whyItMatters: 'Failed caulk allows water and air infiltration. Proper sealing reduces energy costs and prevents rot and pest entry.',
    estMinutes: 120,
    materials: 'Exterior silicone or polyurethane caulk, caulk gun, scraper',
    safetyNote: 'Work from stable ladder. Use appropriate caulk for outdoor use.',
    appliesIfFreeze: true,
    appliesIfHurricane: true,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'SPRINKLER_WINTERIZE',
    category: 'Exterior',
    taskName: 'Winterize Sprinkler System',
    baseFrequency: 'annually',
    monthsHotHumid: null,
    monthsColdSnow: '9,10',
    monthsMixed: '10,11',
    monthsAridMountain: '10,11',
    seasonalTag: 'fall',
    howTo: '1. Turn off water supply to system\n2. Set timer/controller to off or rain mode\n3. Open manual drain valves\n4. Blow out lines with air compressor (50 PSI max)\n5. Insulate backflow preventer and above-ground components\n6. Document any needed spring repairs',
    whyItMatters: 'Frozen pipes crack and split. One freeze can destroy entire sprinkler system requiring thousands in replacement.',
    estMinutes: 60,
    materials: 'Air compressor, pipe insulation',
    safetyNote: 'Do not exceed 50 PSI - higher pressure damages system components',
    appliesIfFreeze: true,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: true,
    proServiceRecommended: true,
    diyOk: true
  },
  {
    taskCode: 'SPRINKLER_SPRING_START',
    category: 'Exterior',
    taskName: 'Spring Sprinkler System Startup',
    baseFrequency: 'annually',
    monthsHotHumid: '3,4',
    monthsColdSnow: '4,5',
    monthsMixed: '3,4',
    monthsAridMountain: '4,5',
    seasonalTag: 'spring',
    howTo: '1. Remove insulation from components\n2. Close all manual drain valves\n3. Slowly turn on water supply\n4. Check for leaks at all connections\n5. Run each zone manually\n6. Check head coverage and adjust as needed\n7. Program controller for season',
    whyItMatters: 'Proper startup prevents water waste, ensures even coverage, and catches winter damage before it causes lawn problems.',
    estMinutes: 45,
    materials: null,
    safetyNote: 'Open water supply slowly to prevent water hammer',
    appliesIfFreeze: true,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: true,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'SMOKE_DETECTOR_TEST',
    category: 'Safety',
    taskName: 'Test Smoke and CO Detectors',
    baseFrequency: 'monthly',
    monthsHotHumid: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsColdSnow: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsMixed: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsAridMountain: '1,2,3,4,5,6,7,8,9,10,11,12',
    seasonalTag: null,
    howTo: '1. Press test button on each detector\n2. Verify loud alarm sounds\n3. Replace batteries if alarm is weak or chirping\n4. Vacuum dust from detector vents\n5. Check manufacture date (replace after 10 years)\n6. Ensure detectors on each floor and near bedrooms',
    whyItMatters: 'Working smoke detectors reduce fire death risk by 55%. CO detectors prevent silent poisoning from faulty furnaces and appliances.',
    estMinutes: 15,
    materials: '9V batteries or 10-year sealed batteries',
    safetyNote: 'Never disable detector due to false alarms - relocate instead',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'FIRE_EXTINGUISHER_CHECK',
    category: 'Safety',
    taskName: 'Check Fire Extinguishers',
    baseFrequency: 'monthly',
    monthsHotHumid: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsColdSnow: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsMixed: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsAridMountain: '1,2,3,4,5,6,7,8,9,10,11,12',
    seasonalTag: null,
    howTo: '1. Check that extinguisher is in designated location\n2. Verify pressure gauge is in green zone\n3. Inspect for damage, rust, or dents\n4. Ensure pin and seal are intact\n5. Tip upside down and shake to prevent powder settling\n6. Replace if over 12 years old',
    whyItMatters: 'A working extinguisher can stop a small fire before it becomes a disaster. Non-working units give false sense of security.',
    estMinutes: 10,
    materials: null,
    safetyNote: 'Know PASS technique: Pull, Aim, Squeeze, Sweep',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: true,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'DRYER_VENT_CLEAN',
    category: 'Appliance',
    taskName: 'Clean Dryer Vent Duct',
    baseFrequency: 'annually',
    monthsHotHumid: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsColdSnow: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsMixed: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsAridMountain: '1,2,3,4,5,6,7,8,9,10,11,12',
    seasonalTag: null,
    howTo: '1. Pull dryer away from wall\n2. Disconnect vent hose from dryer and wall\n3. Use dryer vent brush kit to clean duct\n4. Clean behind dryer\n5. Check exterior vent flap operates freely\n6. Reconnect and push dryer back',
    whyItMatters: 'Lint buildup causes 15,000+ house fires yearly. Clean vents also improve dryer efficiency and reduce drying time.',
    estMinutes: 45,
    materials: 'Dryer vent brush kit, vacuum',
    safetyNote: 'Unplug dryer before moving. Gas dryers: turn off gas valve first.',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: true,
    diyOk: true
  },
  {
    taskCode: 'FRIDGE_COILS_CLEAN',
    category: 'Appliance',
    taskName: 'Clean Refrigerator Coils',
    baseFrequency: 'annually',
    monthsHotHumid: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsColdSnow: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsMixed: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsAridMountain: '1,2,3,4,5,6,7,8,9,10,11,12',
    seasonalTag: null,
    howTo: '1. Unplug refrigerator\n2. Locate coils (back or bottom of unit)\n3. Use coil brush to loosen dust\n4. Vacuum debris thoroughly\n5. Wipe down with damp cloth\n6. Plug back in',
    whyItMatters: 'Dirty coils make compressor work harder, increasing energy use by 25% and shortening refrigerator life.',
    estMinutes: 30,
    materials: 'Coil brush, vacuum with crevice tool',
    safetyNote: 'Unplug before cleaning',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'DISHWASHER_CLEAN',
    category: 'Appliance',
    taskName: 'Clean Dishwasher Filter and Interior',
    baseFrequency: 'monthly',
    monthsHotHumid: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsColdSnow: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsMixed: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsAridMountain: '1,2,3,4,5,6,7,8,9,10,11,12',
    seasonalTag: null,
    howTo: '1. Remove bottom rack\n2. Twist and remove filter assembly\n3. Rinse filter under running water\n4. Scrub with soft brush if needed\n5. Check spray arms for clogs\n6. Run empty cycle with 1 cup vinegar in top rack\n7. Wipe door seals with damp cloth',
    whyItMatters: 'Clogged filters cause poor cleaning, odors, and can damage pump. Regular maintenance extends dishwasher life.',
    estMinutes: 20,
    materials: 'White vinegar, soft brush',
    safetyNote: null,
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: true,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'WASHING_MACHINE_CLEAN',
    category: 'Appliance',
    taskName: 'Clean Washing Machine',
    baseFrequency: 'monthly',
    monthsHotHumid: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsColdSnow: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsMixed: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsAridMountain: '1,2,3,4,5,6,7,8,9,10,11,12',
    seasonalTag: null,
    howTo: '1. Run empty hot cycle with 2 cups white vinegar\n2. Wipe gasket/seals with vinegar solution\n3. Clean detergent dispenser\n4. Leave door open after to dry\n5. Check inlet hose filters for debris',
    whyItMatters: 'Prevents mold, mildew, and musty odors. Front-loaders are especially prone to seal mold if not maintained.',
    estMinutes: 15,
    materials: 'White vinegar, clean cloth',
    safetyNote: null,
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: true,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'GARBAGE_DISPOSAL_CLEAN',
    category: 'Appliance',
    taskName: 'Clean Garbage Disposal',
    baseFrequency: 'monthly',
    monthsHotHumid: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsColdSnow: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsMixed: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsAridMountain: '1,2,3,4,5,6,7,8,9,10,11,12',
    seasonalTag: null,
    howTo: '1. Turn off disposal and water\n2. Drop ice cubes and salt into disposal\n3. Run cold water and turn on disposal\n4. Grind ice for 30 seconds\n5. Drop in citrus peels for freshness\n6. Flush with cold water for 30 seconds',
    whyItMatters: 'Regular cleaning prevents odors, removes buildup, and keeps blades sharp for better performance.',
    estMinutes: 10,
    materials: 'Ice cubes, salt, lemon or orange peels',
    safetyNote: 'Never put hands in disposal',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'RANGE_HOOD_CLEAN',
    category: 'Appliance',
    taskName: 'Clean Range Hood and Filter',
    baseFrequency: 'quarterly',
    monthsHotHumid: '1,4,7,10',
    monthsColdSnow: '1,4,7,10',
    monthsMixed: '1,4,7,10',
    monthsAridMountain: '1,4,7,10',
    seasonalTag: null,
    howTo: '1. Remove filter(s) from hood\n2. Soak in hot water with dish soap and baking soda\n3. Scrub grease with brush\n4. Wipe down hood exterior and interior\n5. Let filter dry completely\n6. Reinstall filter',
    whyItMatters: 'Grease-clogged filters reduce airflow and become fire hazards. Clean filters remove smoke and odors effectively.',
    estMinutes: 30,
    materials: 'Dish soap, baking soda, scrub brush',
    safetyNote: 'Turn off range before cleaning',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'ATTIC_INSULATION_CHECK',
    category: 'Interior',
    taskName: 'Inspect Attic Insulation',
    baseFrequency: 'annually',
    monthsHotHumid: '1,2',
    monthsColdSnow: '8,9',
    monthsMixed: '8,9',
    monthsAridMountain: '8,9',
    seasonalTag: 'fall',
    howTo: '1. Access attic safely with proper lighting\n2. Check insulation depth (should be 10-14 inches)\n3. Look for bare spots or compressed areas\n4. Check for signs of pests or moisture\n5. Verify insulation covers all areas evenly\n6. Note areas needing additional insulation',
    whyItMatters: 'Proper insulation reduces heating/cooling costs by 10-50%. Gaps and thin spots cause major energy loss.',
    estMinutes: 30,
    materials: 'Flashlight, measuring tape',
    safetyNote: 'Watch footing on joists. Wear mask and long sleeves when near fiberglass.',
    appliesIfFreeze: true,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'WINDOW_WEATHERSTRIP',
    category: 'Interior',
    taskName: 'Check Window and Door Weatherstripping',
    baseFrequency: 'annually',
    monthsHotHumid: '9,10',
    monthsColdSnow: '9,10',
    monthsMixed: '9,10',
    monthsAridMountain: '9,10',
    seasonalTag: 'fall',
    howTo: '1. Close door/window on piece of paper\n2. If paper slides easily, weatherstrip is worn\n3. Remove old weatherstrip\n4. Clean surface thoroughly\n5. Apply new weatherstrip according to type\n6. Test closure and adjust as needed',
    whyItMatters: 'Air leaks around doors and windows can account for 25-30% of heating/cooling loss. Sealing pays for itself quickly.',
    estMinutes: 60,
    materials: 'Replacement weatherstrip (foam, V-strip, or rubber)',
    safetyNote: null,
    appliesIfFreeze: true,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'ELECTRICAL_PANEL_CHECK',
    category: 'Electrical',
    taskName: 'Visual Electrical Panel Inspection',
    baseFrequency: 'annually',
    monthsHotHumid: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsColdSnow: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsMixed: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsAridMountain: '1,2,3,4,5,6,7,8,9,10,11,12',
    seasonalTag: null,
    howTo: '1. Open panel door (no tools needed)\n2. Check for signs of burn marks or discoloration\n3. Look for any rust or corrosion\n4. Ensure all breakers are labeled\n5. Flip each breaker off and on to ensure function\n6. Close panel securely',
    whyItMatters: 'Early detection of electrical issues prevents fires and major damage. Properly labeled panels help in emergencies.',
    estMinutes: 15,
    materials: null,
    safetyNote: 'Never touch wires or breaker connections. Call electrician if you see any damage.',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: true,
    diyOk: true
  },
  {
    taskCode: 'GFCI_TEST',
    category: 'Electrical',
    taskName: 'Test GFCI Outlets',
    baseFrequency: 'monthly',
    monthsHotHumid: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsColdSnow: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsMixed: '1,2,3,4,5,6,7,8,9,10,11,12',
    monthsAridMountain: '1,2,3,4,5,6,7,8,9,10,11,12',
    seasonalTag: null,
    howTo: '1. Locate all GFCI outlets (kitchen, bathrooms, garage, outdoor)\n2. Press TEST button - outlet should click and lose power\n3. Plug in lamp or tester to verify no power\n4. Press RESET button to restore power\n5. Replace any GFCI that fails to trip',
    whyItMatters: 'GFCIs prevent electrocution by cutting power instantly when they detect ground faults. A non-working GFCI provides no protection.',
    estMinutes: 10,
    materials: 'Lamp or outlet tester (optional)',
    safetyNote: 'Replace immediately if GFCI fails test',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'SUMP_PUMP_TEST',
    category: 'Plumbing',
    taskName: 'Test Sump Pump',
    baseFrequency: 'quarterly',
    monthsHotHumid: '1,4,7,10',
    monthsColdSnow: '2,5,8,11',
    monthsMixed: '2,5,8,11',
    monthsAridMountain: null,
    seasonalTag: null,
    howTo: '1. Remove sump pit cover\n2. Pour bucket of water into pit\n3. Float should rise and pump should activate\n4. Watch for water to drain through discharge pipe\n5. Listen for unusual noises\n6. Clean any debris from pit\n7. Replace cover',
    whyItMatters: 'A failed sump pump during heavy rain can flood your basement causing thousands in damage. Regular testing ensures reliability.',
    estMinutes: 15,
    materials: 'Bucket of water',
    safetyNote: 'Never work on pump while it is running',
    appliesIfFreeze: false,
    appliesIfHurricane: true,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'WINTERIZATION',
    category: 'Seasonal',
    taskName: 'Home Winterization Checklist',
    baseFrequency: 'annually',
    monthsHotHumid: null,
    monthsColdSnow: '9,10',
    monthsMixed: '10,11',
    monthsAridMountain: '9,10',
    seasonalTag: 'fall',
    howTo: '1. Disconnect and drain outdoor hoses\n2. Shut off exterior faucet valves if applicable\n3. Check weatherstripping on doors and windows\n4. Reverse ceiling fans to clockwise\n5. Stock emergency supplies (flashlights, batteries)\n6. Have heating system inspected\n7. Test backup power/generator if applicable',
    whyItMatters: 'Proper winterization prevents frozen pipes, reduces heating costs, and prepares home for weather emergencies.',
    estMinutes: 120,
    materials: 'Varies by task',
    safetyNote: null,
    appliesIfFreeze: true,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'SPRING_MAINTENANCE',
    category: 'Seasonal',
    taskName: 'Spring Home Checkup',
    baseFrequency: 'annually',
    monthsHotHumid: '3,4',
    monthsColdSnow: '4,5',
    monthsMixed: '3,4',
    monthsAridMountain: '4,5',
    seasonalTag: 'spring',
    howTo: '1. Walk exterior checking for winter damage\n2. Check foundation for cracks\n3. Clean debris from window wells\n4. Check grading - soil should slope away from foundation\n5. Service lawn mower and outdoor equipment\n6. Check outdoor lighting and replace bulbs\n7. Clean patio furniture',
    whyItMatters: 'Spring inspection catches winter damage early before it worsens. Proper prep ensures home is ready for summer.',
    estMinutes: 120,
    materials: 'Varies by task',
    safetyNote: null,
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  },
  {
    taskCode: 'VENT_CLEAN',
    category: 'Interior',
    taskName: 'Clean HVAC Vents and Registers',
    baseFrequency: 'quarterly',
    monthsHotHumid: '1,4,7,10',
    monthsColdSnow: '1,4,7,10',
    monthsMixed: '1,4,7,10',
    monthsAridMountain: '1,4,7,10',
    seasonalTag: null,
    howTo: '1. Turn off HVAC system\n2. Remove vent covers\n3. Soak in warm soapy water\n4. Vacuum inside duct openings (as far as you can reach)\n5. Wipe vent covers dry\n6. Reinstall covers\n7. Restart system',
    whyItMatters: 'Clean vents improve air quality and airflow. Dust buildup can trigger allergies and reduce HVAC efficiency.',
    estMinutes: 45,
    materials: 'Vacuum with brush attachment, warm soapy water',
    safetyNote: 'Turn off system before removing vents',
    appliesIfFreeze: false,
    appliesIfHurricane: false,
    appliesIfWildfire: false,
    appliesIfHardWater: false,
    appliesIfHasSprinklers: false,
    proServiceRecommended: false,
    diyOk: true
  }
];

async function seedTasks() {
  console.log('Starting maintenance task seeding...');
  
  try {
    const existing = await db.select().from(homeMaintenanceTasksTable);
    
    if (existing.length > 0) {
      console.log(`Tasks already seeded (${existing.length} tasks exist). Skipping.`);
      process.exit(0);
    }
    
    await db.transaction(async (tx) => {
      await tx.insert(homeMaintenanceTasksTable).values(MAINTENANCE_TASKS);
    });
    
    console.log(`Successfully seeded ${MAINTENANCE_TASKS.length} maintenance tasks!`);
    process.exit(0);
  } catch (error) {
    console.error('Failed to seed tasks:', error);
    process.exit(1);
  }
}

seedTasks();
